#!/bin/sh

#SBATCH -n 128              # Request 128 cores
#SBATCH -t 0-12:00:00      # Request 12 hours and 0 minutes
#SBATCH -p compute         # Use the "compute" partition
#SBATCH -J MONCapstone2024     # Job name
#SBATCH -o "Capstone/VOTPP folder/Slurm_2024/slurm-%j.out"
#SBATCH -e "Capstone/VOTPP folder/Slurm_2024/slurm-%j.err"

# Activate the Conda environment
source ~/miniconda3/bin/activate Capstone_conda_env6
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

# Ensure Python output is unbuffered
export PYTHONUNBUFFERED=1

# Run the MPI script for simulation using slurm 
# mpirun -np 128 -hosts=$SLURM_NODELIST python "VOTPP folder/VOTPP_[n-e]-(e).py"
mpirun -np 128 python "VOTPP folder/VOTPP_[n-e]-(n).py"

# # Wait for the simulation to complete before starting plotting
# wait

# # Run the MPI script for plotting using slurm 
# mpirun -np 1 python "VOTPP folder/VOTPP_results_and_fit_plotter.py"
